### PR TITLE
566 Delete preview channel upon merge

### PR DESCRIPTION
**Pull request by jeffplays2005**
Have added the feature to the pre-existing workflow action as per [this pull request on action-hosting-deploy](https://github.com/FirebaseExtended/action-hosting-deploy/pull/65)

### CODE REVIEW

**Comment by jeffplays2005** [comment]
If the above doesn't work, I found another solution:
https://github.com/FirebaseExtended/action-hosting-deploy/issues/60#issuecomment-1761357523

**Comment by bcho892** [comment]
> If the above doesn't work, I found another solution: [FirebaseExtended/action-hosting-deploy#60 (comment)](https://github.com/FirebaseExtended/action-hosting-deploy/issues/60#issuecomment-1761357523)

Prefer this as the current change seems to not have been implemented...

**Comment by jeffplays2005** [comment]
> > If the above doesn't work, I found another solution: [FirebaseExtended/action-hosting-deploy#60 (comment)](https://github.com/FirebaseExtended/action-hosting-deploy/issues/60#issuecomment-1761357523)
> 
> Prefer this as the current change seems to not have been implemented...

Oops, what am I doing... Will make the changes and push soon

**Review by bcho892 — APPROVED** [review]
I don't think this will mess anything up because its our staging instance anyway

**Pull request merged**
