### PR TITLE
285 responsive pricing card

### LINKED ISSUE #285: [FRONTEND] Make pricing cards responsive
**Is your feature request related to a problem? Please describe.**

Image

Assume mobile is < sm breakpoint
i.e
```
<div class="sm:text-center">
  This text will be centered on medium screens, but revert back
  to the default (left-aligned) at all other screen sizes.
</div>
```

**BEFORE MERGING**

- [ ] Storybooks created where possible
- [ ] Tested with [nock](https://tanstack.com/query/v3/docs/framework/react/guides/testing) if data fetching
- [ ] Tests written for critical interactions
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (_hint_: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

### PR DESCRIPTION
**Pull request by zlrkw11**
closes #285

### CODE REVIEW

**Comment by zlrkw11** [comment]
image
- small viewport's default (home) pricing card  
while the lg and md designs are not affected:
image

image
- small viewport's unselected pricing card
image
- small viewport's selected pricing card

**Comment by zlrkw11** [comment]
image
- implemented the divider. Made small changes compared to Figma to make the card look more balanced overall. it will be hidden on Lg and md viewport.

**Comment by bcho892** [comment]
can you check all the pages where this are being used as well (by booting up the actual site)

**Review by bcho892 — APPROVED** [review]

**Review by bcho892 — CHANGES_REQUESTED** [review]
Screenshot_20240522-011024

Seems like some text is cut off on smaller screens

**Review by bcho892 — APPROVED** [review]
gj i like the design for small screens

**Comment by zlrkw11** [comment]
image
- galaxy Z fold 5

**Pull request merged**
